=== provenant-dev/vLEI/schema/acdc/campaign-credential.json
{
  "$id": "EF-2niGwOfhDSb0qQBLhmHtY8z0cYVy4kCDHC9c8r0ME",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Campaign Credential",
  "description": "A Campaign Credential issued to a Brand for A2P 10DLC messaging campaigns",
  "type": "object",
  "credentialType": "CampaignCredential",
  "version": "1.0.0",
  "properties": {
    "v": {
      "description": "Version",
      "type": "string"
    },
    "d": {
      "description": "Credential SAID",
      "type": "string"
    },
    "u": {
      "description": "One time use nonce",
      "type": "string"
    },
    "i": {
      "description": "Issuer AID",
      "type": "string"
    },
    "ri": {
      "description": "Credential status registry",
      "type": "string"
    },
    "s": {
      "description": "Schema SAID",
      "type": "string"
    },
    "a": {
      "oneOf": [
        {
          "description": "Attributes block SAID",
          "type": "string"
        },
        {
          "$id": "EPbSye1QF8JN-YRpCNFiYYJTMgJkWy7CJR-sQVAiGnQP",
          "description": "Attributes block",
          "type": "object",
          "properties": {
            "d": {
              "description": "Attributes block SAID",
              "type": "string"
            },
            "i": {
              "description": "Recipient Brand AID",
              "type": "string"
            },
            "dt": {
              "description": "Issuance date time",
              "format": "date-time",
              "type": "string"
            },
            "brandId": {
              "description": "The brand identifier to use with the campaign (e.g., LEI of the Brand)",
              "type": "string"
            },
            "campaignId": {
              "description": "Unique campaign identifier",
              "type": "string"
            },
            "campaignDescription": {
              "description": "Description about the campaign",
              "type": "string"
            },
            "campaignType": {
              "description": "Campaign type",
              "type": "string"
            },
            "startDate": {
              "description": "Campaign start date",
              "format": "date-time",
              "type": "string"
            },
            "expirationDate": {
              "description": "Campaign expiration date",
              "format": "date-time",
              "type": "string"
            },
            "telephoneNumbers": {
              "description": "Telephone Numbers for the campaign",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "tn": {
                    "type": "string",
                    "description": "Telephone number in E164 format"
                  }
                },
                "additionalProperties": false,
                "required": [
                  "tn"
                ]
              }
            },
            "authorizedServiceProvider": {
              "description": "Authorized service provider",
              "type": "string"
            },
            "campaignAttributes": {
              "description": "The Campaign and content attributes object contains a series of Yes or No questions related to the particular features of the campaign",
              "type": "object",
              "properties": {
                "subscriberOptIn": {
                  "description": "Indicate whether campaign collect and process customer opt-ins",
                  "type": "string"
                },
                "subscriberOptOut": {
                  "description": "Indicate whether campaign collect and process customer opt-outs",
                  "type": "string"
                },
                "subscriberHelp": {
                  "description": "Indicate whether subscribers can contact the message sender after sending the HELP keyword",
                  "type": "string"
                },
                "embeddedLink": {
                  "description": "Indicate whether campaign messages will use an embedded link",
                  "type": "string"
                },
                "affiliateMarketing": {
                  "description": "Indicate whether the campaign involves affiliate marketing",
                  "type": "string"
                }
              },
              "additionalProperties": true,
              "required": [
                "subscriberOptIn",
                "subscriberOptOut",
                "subscriberHelp"
              ]
            }
          },
          "additionalProperties": false,
          "required": [
            "i",
            "dt",
            "brandId",
            "campaignId",
            "campaignDescription",
            "campaignType",
            "startDate",
            "expirationDate",
            "telephoneNumbers",
            "authorizedServiceProvider",
            "campaignAttributes"
          ]
        }
      ]
    },
    "e": {
      "oneOf": [
        {
          "description": "Edges block SAID",
          "type": "string"
        },
        {
          "$id": "EJrEovSBvm4odgfVI9zldtlju8_lD2m1gDiryDqvB8Lt",
          "description": "Edges block",
          "type": "object",
          "properties": {
            "d": {
              "description": "Edges block SAID",
              "type": "string"
            },
            "le": {
              "description": "Chain to legal entity vLEI credential",
              "type": "object",
              "properties": {
                "n": {
                  "description": "SAID of Legal Entity vLEI Credential issued by a Qualified vLEI issuer to a Legal Entity",
                  "type": "string"
                },
                "s": {
                  "description": "SAID of Legal Entity vLEI Credential schema",
                  "type": "string",
                  "const": "ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY"
                }
              },
              "additionalProperties": false,
              "required": [
                "n",
                "s"
              ]
            }
          },
          "additionalProperties": false,
          "required": [
            "d",
            "le"
          ]
        }
      ]
    },
    "r": {
      "oneOf": [
        {
          "description": "Rules block SAID",
          "type": "string"
        },
        {
          "$id": "ECllqarpkZrSIWCb97XlMpEZZH3q4kc--FQ9mbkFMb_5",
          "description": "Rules block",
          "type": "object",
          "properties": {
            "d": {
              "description": "Rules block SAID",
              "type": "string"
            },
            "usageDisclaimer": {
              "description": "Usage Disclaimer",
              "type": "object",
              "properties": {
                "l": {
                  "description": "Associated legal language",
                  "type": "string",
                  "const": "Usage of a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, does not assert that the Legal Entity is trustworthy, honest, reputable in its business dealings, safe to do business with, or compliant with any laws or that an implied or expressly intended purpose will be fulfilled."
                }
              }
            },
            "issuanceDisclaimer": {
              "description": "Issuance Disclaimer",
              "type": "object",
              "properties": {
                "l": {
                  "description": "Associated legal language",
                  "type": "string",
                  "const": "All information in a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, is accurate as of the date the validation process was complete. The vLEI Credential has been issued to the legal entity or person named in the vLEI Credential as the subject; and the qualified vLEI Issuer exercised reasonable care to perform the validation process set forth in the vLEI Ecosystem Governance Framework."
                }
              }
            }
          },
          "additionalProperties": false,
          "required": [
            "d",
            "usageDisclaimer",
            "issuanceDisclaimer"
          ]
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "i",
    "ri",
    "s",
    "d",
    "e",
    "r"
  ]
}

=== provenant-dev/vLEI/samples/acdc/campaign-credential.json
{
  "v": "ACDC10JSON0004e4_",
  "d": "EuF1gpodKbbqS0fqmUiOYf-MusuNvi0OmY8Js6SKSdfE",
  "i": "EKXPX7hWw8KK5Y_Mxs2TOuCrGdN45vPIZ78NofRlVBws",
  "ri": "EuqwB_iOD86eK0ynAhA6AYwWvPeBhvmbcmOD-9cCmiVU",
  "s": "EF-2niGwOfhDSb0qQBLhmHtY8z0cYVy4kCDHC9c8r0ME",
  "a": {
    "d": "E9-86Jag34CrJpfNFz_-7E5HA0Dj0FvcYNoFVe7qwkiI",
    "dt": "2022-08-25T14:07:30.536257+00:00",
    "i": "EY4ldIBDZP4Tpnm3RX320BO0yz8Uz2nUSN-C409GnCJM",
    "brandId": "6383001AJTYIGC8Y1X37",
    "campaignId": "4d3601ed-c632-4979-ae22-43854ef4ffaf",
    "campaignDescription": "Customer outreach campaign",
    "campaignType": "Automated message",
    "startDate": "2023-02-10T14:06:30.536257+00:00",
    "expirationDate": "2022-03-05T14:00:00.000000+00:00",
    "telephoneNumbers": [
      {
        "tn": "+447860041117"
      }
    ],
    "authorizedServiceProvider": "Acme Inc.",
    "campaignAttributes": {
      "subscriberOptIn": "Yes",
      "subscriberOptOut": "No",
      "subscriberHelp": "Yes",
      "embeddedLink": "No",
      "affiliateMarketing": "Yes"
    }
  },
  "e": {
    "d": "EsOf5_YgX_64z4YuHNFWLUnIKcyvsVQOe_vJ_638X6gE",
    "le": {
      "n": "ESyLzoJC4L_1abXOEN4f6uNZCmhqyEHg2geBHFhJ8KDs",
      "s": "ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY"
    }
  },
  "r": {
    "d": "EDIai3Wkd-Z_4cezz9nYEcCK3KNH5saLvZoS_84JL6NU",
    "usageDisclaimer": {
      "l": "Usage of a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, does not assert that the Legal Entity is trustworthy, honest, reputable in its business dealings, safe to do business with, or compliant with any laws or that an implied or expressly intended purpose will be fulfilled."
    },
    "issuanceDisclaimer": {
      "l": "All information in a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, is accurate as of the date the validation process was complete. The vLEI Credential has been issued to the legal entity or person named in the vLEI Credential as the subject; and the qualified vLEI Issuer exercised reasonable care to perform the validation process set forth in the vLEI Ecosystem Governance Framework."
    }
  }
}
